- name: deploy base services
  hosts: local, cloud
  gather_facts: no
  become: yes
  become_user: "root"
  roles:
    - { role: bootstrap, tags: ['bootstrap']}
    - { role: networking, tags: ['networking']}
    - { role: podman, tags: ['podman']}

- name: deploy databases
  hosts: local, cloud
  gather_facts: no
  become: yes
  become_user: "root"
  roles:
    - { role: postgresql, tags: ['postgresql', 'databases']}

- name: deploy fast-only databases
  hosts: fast
  gather_facts: no
  become: yes
  become_user: "root"
  roles:
    - { role: mysql, tags: ['mysql', 'databases']}
    - { role: mssql, tags: ['mssql', 'databases']}

- name: deploy heavy-only databases
  hosts: heavy
  gather_facts: no
  become: yes
  become_user: "root"
  roles:
    - { role: oracle, tags: ['oracle', 'databases']}

- name: deploy jenkins, front-facing services
  hosts: local
  gather_facts: no
  become: yes
  become_user: "root"
  roles:
    # BUG: these two roles are mutually dependent on each other, paths
    # + usernames.  need to fix that.  right now, have to run both individually,
    # let them error out, rerun
    - { role: scripts, tags: ['scripts']}
    - { role: jenkins, tags: ['jenkins']}

- name: deploy special jenkins linode files
  hosts: public_facing
  gather_facts: no
  become: yes
  become_user: root
  roles:
    - { role: public_scripts, tags: ['scripts', 'public_scripts']}

- name: deploy jenkins cloud, front-facing services
  hosts: cloud
  gather_facts: no
  become: yes
  become_user: "root"
  roles:
    - { role: jenkins_cloud, tags: ['jenkins']}
    - { role: scripts, tags: ['scripts']}

