#!/bin/sh

# background:
# http://melikedev.com/2013/08/19/linux-selinux-semodule-compile-pp-module-from-te-file/
# https://www.centos.org/docs/5/html/Deployment_Guide-en-US/sec-sel-building-policy-module.html

# $ -> cd ~
# $ -> echo > /var/log/audit/audit.log # this ensures a clean log for analysis
# $ -> /etc/init.d/puppetmaster start # should fail
# $ -> audit2allow -i /var/log/audit/audit.log -m puppetmaster # this will output the perms necessary for puppetmaster to access needed resources, copy and paste this into the file you are using in version control
# $ -> checkmodule -M -m -o puppetmaster.mod /path/to/your/version/controlled/puppetmaster.te # this will create a .mod file
# $ -> semodule_package -m puppetmaster.mod -o puppetmaster.pp # this will create a compiled semodule
# $ -> semodule -i puppetmaster.pp # this will install the module

oraclexe=`semodule -l | grep oraclexe`


if [[ $oraclexe != '' ]]; then
  exit 0
fi

# generated by audit2allow
cat << EOF > /tmp/oraclexe.te

module oraclexe 1.0;

require {
	type container_file_t;
	type container_t;
	class chr_file execute;
}

#============= container_t ==============

#!!!! The file '/dev/zero' is mislabeled on your system.
#!!!! Fix with $ restorecon -R -v /dev/zero
allow container_t container_file_t:chr_file execute;
EOF


cd /tmp/
checkmodule -M -m -o oraclexe.mod oraclexe.te
semodule_package -m oraclexe.mod -o oraclexe.pp
semodule -i oraclexe.pp
semodule -e oraclexe