#!/bin/sh

# background:
# http://melikedev.com/2013/08/19/linux-selinux-semodule-compile-pp-module-from-te-file/
# https://www.centos.org/docs/5/html/Deployment_Guide-en-US/sec-sel-building-policy-module.html

# https://bugzilla.redhat.com/show_bug.cgi?id=1362244#c13

# $ setenforce permissive
# $ -> cd ~
# $ -> echo > /var/log/audit/audit.log # this ensures a clean log for analysis
# $ semodule -DB  # FROM THE BUGZILLA, TURN OFF DONTAUDIT RULES
# $ -> /etc/init.d/puppetmaster start # should show denials in log
# $ semodule -B, TURN BACK ON
# $ -> audit2allow -i /var/log/audit/audit.log -m puppetmaster # this will output the perms necessary for puppetmaster to access needed resources, copy and paste this into the file you are using in version control
# $ -> checkmodule -M -m -o puppetmaster.mod /path/to/your/version/controlled/puppetmaster.te # this will create a .mod file
# $ -> semodule_package -m puppetmaster.mod -o puppetmaster.pp # this will create a compiled semodule
# $ -> semodule -i puppetmaster.pp # this will install the module

collectd=`semodule -l | grep collectd_graphite`


if [[ $collectd != '' ]]; then
  exit 0
fi

# generated by audit2allow
cat << EOF > /tmp/collectd_graphite.te

module collectd_graphite 1.0;

require {
	type init_t;
	type collectd_t;
	type lmtp_port_t;
	class process noatsecure;
	class tcp_socket name_connect;
}

#============= collectd_t ==============

#!!!! This avc can be allowed using one of the these booleans:
#     nis_enabled, collectd_tcp_network_connect
allow collectd_t lmtp_port_t:tcp_socket name_connect;

#============= init_t ==============

#!!!! This avc has a dontaudit rule in the current policy
allow init_t collectd_t:process noatsecure;
EOF


cd /tmp/
checkmodule -M -m -o collectd_graphite.mod collectd_graphite.te
semodule_package -m collectd_graphite.mod -o collectd_graphite.pp
semodule -i collectd_graphite.pp
semodule -e collectd_graphite